version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./dev.db:/app/dev.db
    env_file:
      - .env
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate dev --name init &&
             npm run dev"
